spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: serializer.AvroSpecificSerializer
      client-id: stats.collector

collector:
  kafka:
    topics:
      user-actions: stats.user-actions.v1

grpc:
  server:
    port: 0