grpc:
  server:
    port: 0
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  kafka:
    config:
      bootstrap-servers: "kafka:29092"

      user-action-consumer:
        group-id: "action-analyzer-group"
        client-id: "action-consumer-1"
        key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
        value-deserializer: "ru.practicum.avro.UserActionDeserializer"
        attempt-timeout: 1000
        enable-auto-commit: "false"

      event-similarity-consumer:
        group-id: "similarity-analyzer-group"
        client-id: "similarity-consumer-1"
        key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
        value-deserializer: "ru.practicum.avro.EventSimilarityDeserializer"
        attempt-timeout: 1000
        enable-auto-commit: "false"

      user-action-topic: "stats.user-actions.v1"
      events-similarity-topic: "stats.events-similarity.v1"

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://stat-db:5432/ewm-stat
    username: root
    password: root